# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0004_subject_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_id',
            field=models.CharField(default=b'1', max_length=25, unique=False),
        ),
    ]
