# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0005_auto_20170403_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_id',
            new_name='subject_code',
        ),
    ]
