# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-03 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0008_auto_20170403_0747'),
    ]

    operations = [
    ]
