# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0009_auto_20170403_0816'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission', models.BooleanField(default=False)),
                ('profile', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='admission_status',
            field=models.BooleanField(default=False),
        ),
    ]
