# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0011_auto_20170409_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentStatus',
            new_name='StuStatus',
        ),
    ]
