# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-09 19:10
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evo', '0014_auto_20170409_1824'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[[b'p', b'Permanent'], [b'c', b'Correspondence']], default=b'p', max_length=1, verbose_name=b'Address Type')),
                ('village', models.CharField(max_length=70, verbose_name=b'Village/City/Town')),
                ('postoffice', models.CharField(max_length=70, verbose_name=b'Post Office')),
                ('tehsil', models.CharField(max_length=70, verbose_name=b'Tehsil')),
                ('district', models.CharField(max_length=50, verbose_name=b'District')),
                ('state', models.CharField(max_length=50, verbose_name=b'State')),
                ('pincode', models.CharField(max_length=6, validators=[django.core.validators.MinLengthValidator(6)], verbose_name=b'Pin Code')),
                ('mobile', models.CharField(max_length=20, verbose_name=b'Phone/Mobile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentBasic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12, verbose_name=b'Addhar Number')),
                ('first_name', models.CharField(max_length=150, verbose_name=b'First Name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name=b'Last Name')),
                ('fathers_name', models.CharField(max_length=150, verbose_name=b"Father's Name")),
                ('mothers_name', models.CharField(max_length=150, verbose_name=b"Mother's Name")),
                ('dob', models.DateField(verbose_name=b'Date Of Birth')),
                ('gender', models.CharField(choices=[[b'm', b'Male'], [b'f', b'Female']], default=b'm', max_length=1, verbose_name=b'Gender')),
                ('category', models.CharField(choices=[[b'gen', b'General'], [b'sc', b'Scheduled Caste'], [b'st', b'Scheduled Tribe'], [b'irdp', b'Integrated Rural Development Programme']], default=b'gen', max_length=4, verbose_name=b'Category')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_basic', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
