# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 02:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0021_studentqualifications'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentQualifications',
            new_name='StudentQualification',
        ),
    ]
