# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-16 03:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0022_auto_20170416_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqualification',
            name='course',
            field=models.CharField(choices=[[b't', b'10Th'], [b'pt', b'10+2']], max_length=3),
        ),
        migrations.AlterField(
            model_name='studentqualification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentqualification', to=settings.AUTH_USER_MODEL),
        ),
    ]
