# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 01:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evo', '0023_auto_20170416_0341'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_image', models.ImageField(height_field=230, max_length=b'120', upload_to=b'stu_images/', width_field=200)),
                ('signature', models.ImageField(height_field=60, max_length=b'120', upload_to=b'stu_images/', width_field=140)),
                ('tenth', models.ImageField(height_field=850, max_length=b'120', upload_to=b'stu_doc/', width_field=600)),
                ('plustwo', models.ImageField(height_field=850, max_length=b'120', upload_to=b'stu_doc/', width_field=600)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
