# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0024_studentuploads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuploads',
            name='plustwo',
            field=models.ImageField(max_length=120, upload_to=b'stu_doc/'),
        ),
        migrations.AlterField(
            model_name='studentuploads',
            name='signature',
            field=models.ImageField(max_length=120, upload_to=b'stu_images/'),
        ),
        migrations.AlterField(
            model_name='studentuploads',
            name='stu_image',
            field=models.ImageField(max_length=120, upload_to=b'stu_images/'),
        ),
        migrations.AlterField(
            model_name='studentuploads',
            name='tenth',
            field=models.ImageField(max_length=120, upload_to=b'stu_doc/'),
        ),
    ]
