# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-17 04:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evo', '0025_auto_20170417_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuploads',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_uploads', to=settings.AUTH_USER_MODEL),
        ),
    ]
