# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('link', models.URLField()),
                ('index', models.IntegerField(default=1)),
                ('menu', models.ManyToManyField(to='woark.Menu')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
