# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woark', '0002_menu_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='link',
            field=models.URLField(default=b'http://localhost'),
        ),
    ]
