# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woark', '0003_auto_20170310_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='name',
            new_name='title',
        ),
    ]
