# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woark', '0010_auto_20170321_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('link', models.URLField()),
                ('dev', models.CharField(max_length=100)),
                ('dev_link', models.URLField()),
            ],
        ),
    ]
