# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-27 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woark', '0011_themeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='articletag',
            name='blog',
            field=models.ManyToManyField(to='woark.Blog'),
        ),
    ]
