# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-19 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woark', '0012_articletag_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default=b'', upload_to=b'article/<built-in function id>/'),
        ),
    ]
